---
version: 3
images:
  base_image:
    name: quay.io/fedora/fedora:latest
dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
    - openssh-clients
    - sshpass
options:
  package_manager_path: /usr/bin/dnf

# ---
# version: 1
# build_arg_defaults:
#  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8'


# ansible_config: './ansible.cfg'
# dependencies:
#  galaxy: requirements.yml
#  python: requirements.txt


# additional_build_steps:
#  prepend: |
#    RUN pip3 install --upgrade pip setuptools
#  append:
#    - RUN ls -la /etc
# ---
# version: 3
# images:
#   base_image:
#     name: quay.io/fedora/fedora:latest
# dependencies:
#   galaxy: requirements.yml
#   python: requirements.txt
#   ansible_core:
#     package_pip: ansible-core
#   ansible_runner:
#     package_pip: ansible-runner
#   system:
#     - openssh-clients
#     - sshpass
# options:
#   package_manager_path: /usr/bin/dnf
  
