---
version: 3
images:
  base_image:
    name: quay.io/fedora/fedora:latest
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
    - openssh-clients
    - sshpass
options:
  package_manager_path: /usr/bin/dnf
  